### ISSUE TITLE
Server Api Tests

### ISSUE THREAD

**Issue by SzHHard** [SzHHard/todoList#1]
Need to implement Tests for:

Succesfull Calls:

* [x] GET '/tasks' - 200 on success
* [x] GET '/tasks/:id'- 200 on success
* [x] POST '/tasks' - 201 on success
* [x] PUT '/tasks': (update a task to be completed or non-completed) - 200 on successs
* [x] DELETE '/tasks/:id' - 204? on success

Sad Paths:

* [x] GET '/tasks/:id' - 400 if invalid task id
* [x] DELETE '/tasks/:id' - 400 if invalid task id
* [x] PUT '/tasks/:id' - 400 if invalid task id

**Comment by Latrasis** [comment]
Work finished at: 3beda67
